namespace $ {
	export class $mol_avatar_demo extends $mol_example_small {
		
		/**
		 * ```tree
		 * title \Avatar uniquely-generated by id
		 * ```
		 */
		title() {
			return "Avatar uniquely-generated by id"
		}
		
		/**
		 * ```tree
		 * sub /
		 * 	<= Avatar_id_label
		 * 	<= Avatar_label
		 * ```
		 */
		sub() {
			return [
				this.Avatar_id_label(),
				this.Avatar_label()
			] as readonly any[]
		}
		
		/**
		 * ```tree
		 * tags /
		 * 	\avatar
		 * 	\generated
		 * 	\identity
		 * 	\user
		 * ```
		 */
		tags() {
			return [
				"avatar",
				"generated",
				"identity",
				"user"
			] as readonly any[]
		}
		
		/**
		 * ```tree
		 * aspects / \Widget/Draw
		 * ```
		 */
		aspects() {
			return [
				"Widget/Draw"
			] as readonly any[]
		}
		
		/**
		 * ```tree
		 * avatar_id? \$mol_avatar
		 * ```
		 */
		@ $mol_mem
		avatar_id(next?: any) {
			if ( next !== undefined ) return next as never
			return "$mol_avatar"
		}
		
		/**
		 * ```tree
		 * Avatar_id_value $mol_string value? <=> avatar_id?
		 * ```
		 */
		@ $mol_mem
		Avatar_id_value() {
			const obj = new this.$.$mol_string()
			
			obj.value = (next?: any) => this.avatar_id(next)
			
			return obj
		}
		
		/**
		 * ```tree
		 * Avatar_id_label $mol_labeler
		 * 	title \Id
		 * 	content / <= Avatar_id_value
		 * ```
		 */
		@ $mol_mem
		Avatar_id_label() {
			const obj = new this.$.$mol_labeler()
			
			obj.title = () => "Id"
			obj.content = () => [
				this.Avatar_id_value()
			] as readonly any[]
			
			return obj
		}
		
		/**
		 * ```tree
		 * Avatar $mol_avatar id <= avatar_id
		 * ```
		 */
		@ $mol_mem
		Avatar() {
			const obj = new this.$.$mol_avatar()
			
			obj.id = () => this.avatar_id()
			
			return obj
		}
		
		/**
		 * ```tree
		 * Avatar_label $mol_labeler
		 * 	title \Avatar
		 * 	content / <= Avatar
		 * ```
		 */
		@ $mol_mem
		Avatar_label() {
			const obj = new this.$.$mol_labeler()
			
			obj.title = () => "Avatar"
			obj.content = () => [
				this.Avatar()
			] as readonly any[]
			
			return obj
		}
	}
	
}

