namespace $ {
	
	export type $mol_style_pseudo_class =
	| ':active'
	| ':any'
	| ':any-link'
	| ':checked'
	| ':default'
	| ':defined'
	| ':dir(rtl)'
	| ':dir(ltr)'
	| ':disabled'
	| ':empty'
	| ':enabled'
	| ':first'
	| ':first-child'
	| ':first-of-type'
	| ':fullscreen'
	| ':focus'
	| ':focus-visible'
	| ':focus-within'
	| ':hover'
	| ':indeterminate'
	| ':in-range'
	| ':invalid'
	| ':last-child'
	| ':last-of-type'
	| ':left'
	| ':link'
	| ':not()'
	| ':nth-child(even)'
	| ':nth-child(odd)'
	| ':nth-last-child(even)'
	| ':nth-last-child(odd)'
	| ':nth-of-type(even)'
	| ':nth-of-type(odd)'
	| ':nth-last-of-type(even)'
	| ':nth-last-of-type(odd)'
	| ':only-child'
	| ':only-of-type'
	| ':optional'
	| ':out-of-range'
	| ':read-only'
	| ':read-write'
	| ':required'
	| ':right'
	| ':root'
	| ':scope'
	| ':target'
	| ':valid'
	| ':visited'

}
